### ISSUE TITLE
Foundry V11 Crashes Container

### ISSUE THREAD

**Issue by N0S1gnal** [thomasfa18/node-foundry#3]
**Steps to Reproduce**
1. Deploy via Docker per steps on Foundry VTT Wiki: https://foundryvtt.wiki/en/setup/hosting/Docker#thomasfa18s-dockerhub-image
2. Click Run

**Expected Behavior**
Container runs and requests license key on webpage (Foundry v10 runs just fine)

**Actual Behavior**
Container crashes
Behavior is exhibited on both a Synology NAS and Windows machine running Docker

Foundry VTT version: 11.307
Container: thomasfa18/node-foundry:latest

**Log output (also attached as CSV)**
``Node.js v17.3.0
}
code: [32m'ERR_DLOPEN_FAILED'[39m
[90m at Module.load (node:internal/modules/cjs/loader:975:32)[39m {
[90m at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)[39m
[90m at Module._compile (node:internal/modules/cjs/loader:1097:14)[39m
at Object.<anonymous> (/pkg/resources/app/node_modules/[4mclassic-level[24m/binding.js:1:43)
at load (/pkg/resources/app/node_modules/[4mnode-gyp-build[24m/node-gyp-build.js:22:10)
[90m at require (node:internal/modules/cjs/helpers:102:18)[39m
[90m at Module.require (node:internal/modules/cjs/loader:999:19)[39m
[90m at Function.Module._load (node:internal/modules/cjs/loader:822:12)[39m
[90m at Module.load (node:internal/modules/cjs/loader:975:32)[39m
[90m at Object.Module._extensions..node (node:internal/modules/cjs/loader:1179:18)[39m
Error: Error relocating /pkg/resources/app/node_modules/classic-level/prebuilds/linux-x64/node.napi.musl.node: _ZSt28__throw_bad_array_new_lengthv: symbol not found
		^
"  return process.dlopen(module, path.toNamespacedPath(filename));
"
node:internal/modules/cjs/loader:1179
Node.js v17.3.0
}
code: [32m'ERR_MODULE_NOT_FOUND'[39m
[90m at link (node:internal/modules/esm/module_job:78:36)[39m {
[90m at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)[39m
[90m at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)[39m
[90m at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)[39m
[90m at defaultResolve (node:internal/modules/esm/resolve:1005:11)[39m
[90m at moduleResolve (node:internal/modules/esm/resolve:910:18)[39m
[90m at packageResolve (node:internal/modules/esm/resolve:864:9)[39m
[90m at new NodeError (node:internal/errors:371:5)[39m
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'proper-lockfile' imported from /pkg/resources/app/dist/init.mjs
	^
	ErrorCaptureStackTrace(err);
node:internal/errors:464
Node.js v17.3.0``

[foundry-test.csv](https://github.com/thomasfa18/node-foundry/files/12345738/foundry-test.csv)

**Comment by N0S1gnal** [comment]
per TwilightDirge's [fork](https://github.com/TwilightDirge/node-foundry), updating ``node:current-alpine3.15`` to ``node:current-alpine3.17`` resolved the crash.

verified that using Docker image built from the fork enables FoundryVTT v11.307 to run without issue.

**Comment by thomasfa18** [comment]
thanks! fixed
